### ISSUE TITLE
delete policy-options prefix-list not working on junos_config

### ISSUE THREAD

**Issue by devopsbae** [Juniper/ansible-junos-stdlib#147]
Hello,

I'm able to run a set command to block an IP, but the delete command is not working from the ansible-playbook. Any ideas?

**Comment by stianvi** [comment]
Solved in
https://github.com/ansible/ansible-modules-core/pull/4031
Merged into ansible:devel and should be picked up in 2.1 RC2. 
So please get latest ansible version and try again :)

**Comment by jb376** [comment]
I'm trying to grade to 2.1 rc2 by running "pip install ansible --upgrade" and is not upgrading. I'm currently running version 2.1

**Comment by stianvi** [comment]
try pip install git+https://github.com/ansible/ansible/tree/stable-2.1

**Comment by jb376** [comment]
I managed to install the stable-2.1 now I'm getting ERROR! Missing target hosts

**Comment by jb376** [comment]
I have the current function on my junos_config file and its still not working. 

PLAY RECAP *********************************************************************
test               : ok=1    changed=0    unreachable=0    failed=0


`def diff_config(candidate, config):

    updates = set()

    for line in candidate:
        parts = line.split()
        action = parts[0]
        cfgline = ' '.join(parts[1:])

        if action not in ['set', 'delete']:
            module.fail_json(msg='line must start with either `set` or `delete`')

        elif action == 'set' and cfgline not in config:
            updates.add(line)

        elif action == 'delete' and not config:
            updates.add(line)

        elif action == 'delete':
            for cfg in config:
                if cfg[4:].startswith(cfgline):
                    updates.add(line)

    return list(updates)`

**Comment by jb376** [comment]
I'm running Version ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

still no luck.

**Comment by vnitinv** [comment]
@stianvi Can you help @jb376 with this issue?

**Comment by stianvi** [comment]
@jb376 Could you paste in your playbook yaml file so I could give a try?

There might be people at #ansible@irc.freenode.net that can help more than me.

Just a fyi: The function you have pasted got the wrong indent - but it might just be a copy/paste error.

**Comment by jb376** [comment]
It was a copy/paste error on my end. I'm able to set the IP, but when I try deleting it, it gives me an ok with the green text.

`- name: Get the current time
  hosts: test
  connection: local
  gather_facts: True


  vars_files:
  - /opt/djan/ansible/roles/juniper/vars/main.yml

  tasks:
  - name: Block IP
    junos_config:
      host: "{{ hostvars[inventory_hostname].ansible_host }}"
      lines:
        - delete policy-options prefix-list BLACKLIST-TOOLv2 1.2.3.4/32
      username: "{{ ROOT_USER }}"
      password: "{{ ROOT_PASSWORD }}"
`

**Comment by jb376** [comment]
After doing some testing, the junos_config module is not reading any of the firewall configuration. @stianvi @vnitinv

**Comment by stianvi** [comment]
Works fine for me. 

playbook task:
```
  tasks:
  - name: Block IP
    junos_config:
      lines:
        - delete policy-options prefix-list BLACKLIST-TOOLv2 1.2.3.4/32
      host: "{{ inventory_hostname }}"
```

```
stianv@netlab-sw01-a> show configuration | compare rollback 1
[edit policy-options prefix-list BLACKLIST-TOOLv2]
-   1.2.3.4/32;
```

netconf debug:
```
Aug  5 14:37:53 [NETCONF] - [32005] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:e874925c-3b94-465d-ad0f-1255475a1b44"><load-configuration action="set" format="text"><configuration-set>delete policy-options prefix-list BLACKLIST-TOOLv2 1.2.3.4/32</configuration-set></load-configuration></nc:rpc>]]>]]>
```

@jb376 Could you enable tracefile on your device and list the output?

config for device and how to get the log:

```
stianv@netlab-sw01-a> show configuration system services netconf | display set
set system services netconf ssh
set system services netconf traceoptions file netconf-debug
set system services netconf traceoptions flag all

{master:0}
stianv@netlab-sw01-a> show log netconf-debug
```

**Comment by ruissalo** [comment]
I have exactly the same issue: set commands work ok, delete commands are not applied.
I'm on 2.1.1.0 with this code:

        elif action == 'delete':
            for cfg in config:
                if cfg[4:].startswith(cfgline):
                    updates.add(line)

It seems to be ignoring delete commands on all config sections, not only under policy-options.

**Comment by stacywsmith** [comment]
This is an issue with the `junos_config` module shipped with Ansible core in Ansible >= 2.1. I believe this issue has been resolved in Ansible core. If not, please open an issue against the core module in [Ansible's repository](https://github.com/ansible/ansible/issues).

FYI, the new `juniper_junos_config` module implemented in this repository via #290 also supports configuration in `set` format (including `delete` statements).

If you are including a `delete` statement for a configuration which might not exist on the target Junos device, you may want to include the `ignore_warning: "statement not found"` option.
